---
- hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - name: Docker Pre-Requisites                      ## Pre-Requisites for Docker ##
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
      - python-docker-py
      - python-py
      - python
      - docker
    - name: Docker Enable Start Service                ## Enabling/Starting Docker Service
      systemd:
        name: docker
        enabled: yes
        state: started
        masked: no
    - name: Vagrant Docker Permission                  ## Assigning Suffiient Permissions to Vagrant User
      user:
        name: vagrant
        groups: dockerroot,root
        append: yes
    - name: "Create Hello World Templace File"         ## Template for Nginx Display Content 
      template:
        src: index.j2
        dest: /tmp/index.html
        mode: 0777
